import { afterEach, describe, expect, it, vi } from 'vitest';
import { api } from './api';
import { setAccessToken } from './http';
import { classificationId, pageFromWire, propertyFromWire, wireCatalogQuery } from './portuguese';
import { sampleClassifications, sampleWireProperty } from '../seo/fixture';
const wireAgent={id:'a',nome:'Ana',email:'ana@example.test',cpf:'52998224725',whatsapp:'5565999999999',creci:null,cargo:'CORRETOR',url_foto:null,ativo:true,criado_em:'2026-09-14'};
afterEach(()=>{vi.unstubAllGlobals();setAccessToken(null);});
describe('integração do contrato português',()=>{
 it('envia senha no login e usa token_acesso sem persistência',async()=>{const request=vi.fn().mockResolvedValueOnce(new Response(JSON.stringify({token_acesso:'test-token',tipo_token:'Bearer',corretor:wireAgent}))).mockResolvedValueOnce(new Response(JSON.stringify(wireAgent)));vi.stubGlobal('fetch',request);const session=await api.login('ana@example.test','senha-de-teste');expect(session.agent.role).toBe('AGENT');expect(session.agent.cpf).toBe(wireAgent.cpf);expect(JSON.parse(request.mock.calls[0][1].body)).toEqual({email:'ana@example.test',senha:'senha-de-teste'});expect(request.mock.calls[0][0]).toBe('/api/autenticacao/entrar');await api.me();expect(request.mock.calls[1][1].headers.get('Authorization')).toBe('Bearer test-token');});
 it('resolve classificações dinâmicas sem expor enums como UUIDs',()=>{expect(classificationId('SALA',sampleClassifications.types)).toBe(sampleClassifications.types[0].id);expect(wireCatalogQuery({page:2,limit:9,type:'SALA',purpose:'LOCACAO',city:'Juara'},sampleClassifications)).toContain('tipo_id=11111111-1111-4111-8111-111111111111');expect(wireCatalogQuery({type:'desconhecido'},sampleClassifications)).toBeNull();const p=propertyFromWire(sampleWireProperty);expect(p.typeName).toBe('Salas comerciais');expect(p.media[0].type).toBe('IMAGE');expect(p).not.toHaveProperty('cpf');expect(pageFromWire({itens:[1],total:21,pagina:1,limite:20},v=>v).totalPages).toBe(2);});
 it('envia cliente público sem campos internos nem consentimento inventado',async()=>{const request=vi.fn().mockResolvedValue(new Response('{"id":"c"}'));vi.stubGlobal('fetch',request);await api.createLead({propertyId:'p',leadName:'Cliente',leadPhone:'66999999999',consentGiven:true});expect(request.mock.calls[0][0]).toBe('/api/clientes');expect(JSON.parse(request.mock.calls[0][1].body)).toEqual({imovel_id:'p',nome:'Cliente',telefone:'66999999999',consentimento:true});});
 it('usa os caminhos de mídia autenticados, arquivos multipart e midias_ids',async()=>{const request=vi.fn().mockImplementation(()=>Promise.resolve(new Response('{}')));vi.stubGlobal('fetch',request);await api.uploadMedia('p',[new File(['imagem'],'foto.webp',{type:'image/webp'})]);expect(request.mock.calls[0][0]).toBe('/api/admin/imoveis/p/midias');expect(request.mock.calls[0][1].body.getAll('arquivos')).toHaveLength(1);expect(request.mock.calls[0][1].body.has('files')).toBe(false);await api.reorderMedia('p',['b','a']);expect(JSON.parse(request.mock.calls[1][1].body)).toEqual({midias_ids:['b','a']});});
 it('omite referências inalteradas em PATCH para preservar vínculos históricos inativos',async()=>{
   const lists={...sampleClassifications,types:sampleClassifications.types.map(v=>({...v,ativo:false}))};
   const request=vi.fn<typeof fetch>(async(input)=>{const path=String(input);const itens=path.includes('/tipos-imovel')?lists.types:path.includes('/finalidades-imovel')?lists.purposes:[];return new Response(JSON.stringify(path.includes('/admin/imoveis/')?sampleWireProperty:{itens,total:itens.length,pagina:1,limite:100}));});
   vi.stubGlobal('fetch',request);const previous=propertyFromWire(sampleWireProperty);await api.saveProperty({...previous,description:'Descrição corrigida'},previous.id,previous);
   const body=JSON.parse(request.mock.calls.find(([,options])=>options?.method==='PATCH')![1]!.body as string);expect(body.descricao).toBe('Descrição corrigida');expect(body).not.toHaveProperty('tipo_id');expect(body).not.toHaveProperty('finalidade_id');expect(body).not.toHaveProperty('corretor_id');
 });
 it('preserva os filtros de data do perfil no backend',async()=>{const request=vi.fn().mockResolvedValue(new Response('{"itens":[],"total":0,"pagina":1,"limite":1}'));vi.stubGlobal('fetch',request);await api.listLeads({page:1,limit:1,createdFrom:'2026-09-01T00:00:00Z'});expect(new URL(request.mock.calls[0][0],'https://test').searchParams.get('criado_desde')).toBe('2026-09-01T00:00:00Z');});
});
