import { useCallback, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { ArrowLeft, ArrowUpRight, MapPin, Maximize2, Building2, ShieldCheck } from 'lucide-react';
import { api } from '../../services/api';
import { useResource } from '../../hooks/useResource';
import { area, money, propertyType } from '../../services/format';
import AsyncState from '../../components/AsyncState';
import MediaGallery from '../../components/MediaGallery';
import LeadFormModal from '../../components/LeadFormModal';
import styles from './PropertyDetail.module.css';
export default function PropertyDetail() {
  const { slug = '' } = useParams();
  const load = useCallback(() => api.getProperty(slug), [slug]);
  const { value: property, loading, error, retry } = useResource(load);
  const [contactOpen, setContactOpen] = useState(false);
  return <div className={`container ${styles.page}`}><Link className={styles.back} to="/"><ArrowLeft size={16}/> Voltar aos imóveis</Link><AsyncState loading={loading} error={error} retry={retry}/>{!loading && !error && property && <><div className={styles.heading}><p className="eyebrow">{propertyType[property.type]} · {property.purpose === 'LOCACAO' ? 'Para alugar' : 'À venda'}</p><h1>{property.title}</h1><p className={styles.location}><MapPin size={17}/>{property.neighborhood}, {property.addressCity} — {property.addressState}</p></div><div className={styles.layout}><div><MediaGallery key={property.id} media={property.media} title={property.title}/><div className={styles.facts}><span><Maximize2 size={20}/><strong>{area(property.usableArea)}</strong> de área útil</span><span><Building2 size={20}/><strong>{area(property.totalArea)}</strong> de área total</span></div><section className={styles.section}><h2>Um espaço, muitas possibilidades.</h2><p className={styles.description}>{property.description}</p></section>{Object.keys(property.features).length > 0 && <section className={styles.section}><h2>Características</h2><dl className={styles.features}>{Object.entries(property.features).map(([name,value]) => <div key={name}><dt>{name}</dt><dd>{typeof value === 'boolean' ? value ? 'Sim' : 'Não' : typeof value === 'object' ? JSON.stringify(value) : String(value)}</dd></div>)}</dl></section>}<section className={styles.section}><h2>Localização</h2><p>{property.addressStreet}, {property.addressNumber}<br/>{property.neighborhood} · {property.addressCity}/{property.addressState}</p></section></div><aside className={styles.aside}><div className={styles.contactCard}><p className="eyebrow">{property.purpose === 'LOCACAO' ? 'Valor de locação' : 'Valor de venda'}</p><p className={styles.price}>{money(property.price)}{property.purpose === 'LOCACAO' && <span>/mês</span>}</p><dl className={styles.costs}>{property.condoFee !== null && <div><dt>Condomínio</dt><dd>{money(property.condoFee)}</dd></div>}{property.iptuFee !== null && <div><dt>IPTU informado</dt><dd>{money(property.iptuFee)}</dd></div>}</dl><button className="button" onClick={() => setContactOpen(true)}>Tenho interesse <ArrowUpRight size={18}/></button><p className={styles.contactHint}>Converse diretamente com o corretor.</p><div className={styles.agent}><div className={styles.avatar}>{property.agent.avatarUrl ? <img src={property.agent.avatarUrl} alt=""/> : property.agent.name.charAt(0)}</div><div><strong>{property.agent.name}</strong><span>{property.agent.creci ? `CRECI ${property.agent.creci}` : 'Corretor responsável'}</span></div></div><p className={styles.assurance}><ShieldCheck size={16}/> Seus dados são usados apenas para o atendimento.</p></div><p className={styles.reference}>Referência: {property.id}</p></aside></div>{contactOpen && <LeadFormModal property={property} onClose={() => setContactOpen(false)}/>}</>}</div>;
}
