import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App';
import AppErrorBoundary from './components/AppErrorBoundary';
import { BootstrapContext } from './seo/context';
import { defaultConfig, type Bootstrap } from './seo/metadata';
const element = document.getElementById('seo-bootstrap');
const boot: Bootstrap = element ? JSON.parse(element.textContent!) : { url: '', config: defaultConfig, data: {}, status: 200 };
const app = <React.StrictMode><BootstrapContext.Provider value={boot}><AppErrorBoundary><App/></AppErrorBoundary></BootstrapContext.Provider></React.StrictMode>;
const root = document.getElementById('root')!;
if (element && root.children.length) ReactDOM.hydrateRoot(root, app);
else ReactDOM.createRoot(root).render(app);
