import { useCallback,useState } from 'react';
import { useForm } from 'react-hook-form';
import { z } from 'zod';
import { zodResolver } from '@hookform/resolvers/zod';
import { Navigate } from 'react-router-dom';
import { api } from '../../services/api';
import { useAuth } from '../../hooks/useAuth';
import type { Agent } from '../../types';
import { errorMessage } from '../../services/format';
import AsyncState from '../../components/AsyncState';
import Pagination from '../../components/Pagination';
import Dialog from '../../components/Dialog';
import { useAdminData } from './useAdminData';
import styles from './Admin.module.css';
export const agentSchema=z.object({name:z.string().trim().min(2,'Use pelo menos 2 caracteres.').max(100),email:z.email('Informe um e-mail válido.').max(254),whatsappNumber:z.string().regex(/^[1-9]\d{9,14}$/,'Use DDI e DDD, somente números. Ex.: 5565999999999.'),creci:z.string().max(50),role:z.enum(['ADMIN','AGENT']),avatarUrl:z.string().max(2048).refine(v=>!v||(/^https:\/\//.test(v)&&URL.canParse(v)),'Use uma URL HTTPS válida.'),password:z.string().refine(v=>v===''||(v.length>=12&&v.length<=128&&/\S/.test(v)),'Use entre 12 e 128 caracteres.')});
type Values=z.infer<typeof agentSchema>;
function AgentEditor({agent,onClose,onSaved}:{agent:Agent|null;onClose:()=>void;onSaved:()=>void}){const [error,setError]=useState('');const {register,handleSubmit,setError:setFieldError,formState:{errors,isSubmitting}}=useForm<Values>({resolver:zodResolver(agentSchema),defaultValues:{name:agent?.name??'',email:agent?.email??'',whatsappNumber:agent?.whatsappNumber??'',creci:agent?.creci??'',role:agent?.role??'AGENT',avatarUrl:agent?.avatarUrl??'',password:''}});async function save(v:Values){if(!agent&&!v.password){setFieldError('password',{message:'Defina uma senha de pelo menos 12 caracteres.'});return;}setError('');try{await api.saveAgent({...v,creci:v.creci||null,avatarUrl:v.avatarUrl||null,...(v.password?{password:v.password}:{password:undefined})},agent?.id);onSaved();onClose();}catch(e){setError(errorMessage(e));}}return <Dialog title={agent?'Editar corretor':'Novo corretor'} onClose={()=>{if(!isSubmitting)onClose();}}><form className={styles.form} onSubmit={handleSubmit(save)} noValidate><div className={styles.grid}>{([['name','Nome','text'],['email','E-mail','email'],['whatsappNumber','WhatsApp com DDI e DDD','tel'],['creci','CRECI','text'],['avatarUrl','URL da foto (HTTPS)','url']] as const).map(([name,label,type])=><label key={name}>{label}<input type={type} {...register(name)} aria-invalid={!!errors[name]}/>{errors[name]&&<span className={styles.errorText}>{errors[name]?.message}</span>}</label>)}<label>Permissão<select {...register('role')}><option value="AGENT">Corretor</option><option value="ADMIN">Administrador</option></select></label><label className={styles.wide}>{agent?'Nova senha (opcional)':'Senha *'}<input type="password" autoComplete="new-password" {...register('password')}/><span className={styles.hint}>{agent?'Deixe em branco para manter a senha atual. ':''}Mínimo de 12 caracteres.</span>{errors.password&&<span className={styles.errorText}>{errors.password.message}</span>}</label></div>{error&&<p className="error" role="alert">{error}</p>}<div className={styles.formFooter}><button className="button" disabled={isSubmitting}>{isSubmitting?'Salvando…':'Salvar corretor'}</button><button className="buttonGhost" type="button" onClick={onClose} disabled={isSubmitting}>Cancelar</button></div></form></Dialog>}
export default function AgentsList(){const {agent}=useAuth();const [page,setPage]=useState(1);const [editing,setEditing]=useState<Agent|null|undefined>(undefined);const [mutationError,setMutationError]=useState('');const [busy,setBusy]=useState('');const {data,loading,error,refresh}=useAdminData(useCallback(()=>agent?.role==='ADMIN'?api.listAgents(page,15):Promise.resolve({items:[],total:0,page:1,limit:15,totalPages:0}),[page,agent?.role]));if(agent?.role!=='ADMIN')return <Navigate to="/admin" replace/>;async function toggle(a:Agent){if(!confirm(`${a.active?'Desativar':'Reativar'} a conta de ${a.name}?${a.active?' Os vínculos com imóveis e contatos serão preservados.':''}`))return;setBusy(a.id);setMutationError('');try{await api.saveAgent({name:a.name,email:a.email,whatsappNumber:a.whatsappNumber,role:a.role,creci:a.creci,avatarUrl:a.avatarUrl,active:!a.active},a.id);refresh();}catch(e){setMutationError(errorMessage(e));}finally{setBusy('');}}return <><header className={styles.heading}><div><p className="eyebrow">NOSSA EQUIPE</p><h1>Corretores</h1><p className="muted">Pessoas que conectam espaços e negócios.</p></div><button className="button" onClick={()=>setEditing(null)}>+ Novo corretor</button></header>{mutationError&&<p className="error" role="alert">{mutationError}</p>}<AsyncState loading={loading} error={error} retry={refresh}/>{data&&!error&&<section className={styles.panel}><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Corretor</th><th>Permissão</th><th>Situação</th><th>Ações</th></tr></thead><tbody>{data.items.map(a=><tr key={a.id}><td><strong>{a.name}</strong><small>{a.email}</small><small>{a.creci?`CRECI ${a.creci}`:a.whatsappNumber}</small></td><td>{a.role==='ADMIN'?'Administrador':'Corretor'}</td><td><span className={styles.badge}>{a.active?'Ativo':'Inativo'}</span></td><td><div className={styles.actions}><button className="buttonGhost" onClick={()=>setEditing(a)}>Editar</button><button className="buttonGhost" disabled={!!busy} onClick={()=>void toggle(a)}>{busy===a.id?'Atualizando…':a.active?'Desativar':'Reativar'}</button></div></td></tr>)}</tbody></table></div>{!data.items.length&&<p className={styles.empty}>Nenhum corretor cadastrado.</p>}<Pagination page={page} totalPages={data.totalPages} onChange={setPage}/></section>}{editing!==undefined&&<AgentEditor agent={editing} onClose={()=>setEditing(undefined)} onSaved={refresh}/>}</>}
