import { useCallback, useEffect, useState } from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { useAuth } from '../../hooks/useAuth';
import { api } from '../../services/api';
import { errorMessage } from '../../services/format';
import AsyncState from '../../components/AsyncState';
import Dialog from '../../components/Dialog';
import Pagination from '../../components/Pagination';
import { useAdminData } from './useAdminData';
import { RentalSelector, rentalUi } from './Rentals';
import { commissionSchema, paymentSchema, commissionEditSchema, displayDate, displayMoney, installmentPreview, type Commission, type CommissionInput, type CommissionInstallment, type Lease, type PaymentInput, type RentalOption } from './rentalSchema';

function CommissionEditor({ lease, onClose, onSaved }: { lease?: Lease; onClose: () => void; onSaved: () => void }) {
  const u = rentalUi, { agent } = useAuth();
  const [error, setError] = useState(''), [selecting, setSelecting] = useState(false);
  const [property, setProperty] = useState<RentalOption>({ id: lease?.imovel_id ?? '', nome: lease?.imovel_titulo ?? '' });
  const [client, setClient] = useState<RentalOption>({ id: '', nome: '' });
  const [contract, setContract] = useState<RentalOption>({ id: lease?.id ?? '', nome: lease?.numero_contrato ?? '' });
  const { register, setValue, watch, handleSubmit, formState: { errors, isSubmitting } } = useForm<CommissionInput>({ resolver: zodResolver(commissionSchema), defaultValues: { tipo_operacao: lease ? 'LOCACAO' : 'VENDA', contrato_id: lease?.id ?? '', imovel_id: lease?.imovel_id ?? '', cliente_id: '', valor_total: '', quantidade_parcelas: 1, primeiro_vencimento: '', observacoes: '' } });
  useEffect(()=>{if(!lease?.imovel_id)return;let active=true;setSelecting(true);api.rentalPropertyOption(lease.imovel_id).then(value=>{if(active)setProperty(value);}).catch(failure=>{if(active)setError(errorMessage(failure));}).finally(()=>{if(active)setSelecting(false);});return()=>{active=false;};},[lease?.imovel_id]);
  const operation = watch('tipo_operacao'), total = watch('valor_total'), count = watch('quantidade_parcelas'), date = watch('primeiro_vencimento');
  const preview = installmentPreview(total, count, date);
  async function selectContract(option: RentalOption) {
    setContract(option); setValue('contrato_id', option.id, { shouldValidate: true }); setValue('cliente_id', ''); setClient({ id: '', nome: '' }); setProperty({ id: '', nome: '' }); setValue('imovel_id', '');
    if (!option.imovel_id) return;
    setSelecting(true); setError('');
    try { const selected = await api.rentalPropertyOption(option.imovel_id); setProperty(selected); setValue('imovel_id', selected.id, { shouldValidate: true }); } catch (failure) { setError(errorMessage(failure)); } finally { setSelecting(false); }
  }
  async function save(value: CommissionInput) { setError(''); try { await api.createCommission(value); onSaved(); onClose(); } catch (failure) { setError(errorMessage(failure)); } }
  return <Dialog title="Registrar comissão" onClose={() => { if (!isSubmitting && !selecting) onClose(); }}><form className={u.form} onSubmit={handleSubmit(save)} noValidate><fieldset disabled={isSubmitting || selecting}>
    <p>Informe a receita devida à imobiliária pela intermediação do negócio.</p>
    {!lease && <label>Operação<select {...register('tipo_operacao', { onChange: () => { setValue('contrato_id', ''); setValue('imovel_id', ''); setValue('cliente_id', ''); setContract({ id: '', nome: '' }); setProperty({ id: '', nome: '' }); setClient({ id: '', nome: '' }); } })}><option value="VENDA">Venda</option><option value="LOCACAO">Locação</option></select></label>}
    {lease ? <p>Contrato: {lease.numero_contrato} · {lease.imovel_titulo}</p> : operation === 'LOCACAO' ? <><RentalSelector tipo="CONTRATO" label="Contrato de locação" valor={contract} onSelect={value => void selectContract(value)} /><p className={u.error}>{errors.contrato_id?.message}</p>{property.nome && <p>Imóvel: {property.nome}</p>}</> : <RentalSelector tipo="IMOVEL" label="Imóvel" valor={property} corretor_id={agent?.role === 'ADMIN' ? undefined : agent?.id} onSelect={value => { setProperty(value); setValue('imovel_id', value.id, { shouldValidate: true }); setClient({ id: '', nome: '' }); setValue('cliente_id', ''); }} />}
    <p className={u.error}>{errors.imovel_id?.message}</p>{selecting && <p role="status">Carregando imóvel do contrato…</p>}
    <RentalSelector tipo="CLIENTE" label="Cliente" valor={client} imovel_id={property.id || undefined} corretor_id={property.corretor_id} onSelect={value => { setClient(value); setValue('cliente_id', value.id, { shouldValidate: true }); }} /><p className={u.error}>{errors.cliente_id?.message}</p>
    <p className={u.hint}>O cliente precisa estar ativo e sob o mesmo responsável pelo imóvel. Cadastros manuais sem imóvel também podem ser selecionados.</p>
    <div className={u.grid}><label>Receita total da imobiliária (R$)<input inputMode="decimal" placeholder="Ex.: 1.500,00" {...register('valor_total')} aria-invalid={!!errors.valor_total} /><span className={u.error}>{errors.valor_total?.message}</span></label><label>Quantidade de parcelas<input type="number" min={1} max={600} {...register('quantidade_parcelas', { valueAsNumber: true })} aria-invalid={!!errors.quantidade_parcelas} /><span className={u.error}>{errors.quantidade_parcelas?.message}</span></label><label>Primeiro vencimento<input type="date" {...register('primeiro_vencimento')} aria-invalid={!!errors.primeiro_vencimento} /><span className={u.error}>{errors.primeiro_vencimento?.message}</span></label><label className="col-span-full">Observações<textarea {...register('observacoes')} /><span className={u.error}>{errors.observacoes?.message}</span></label></div>
    {preview.length > 0 && <section className="mt-5 rounded border border-line p-4" aria-label="Prévia das parcelas"><h3>Prévia do parcelamento</h3><ul>{preview.slice(0, 4).map((item, index) => <li key={index}>Parcela {index + 1}: {displayMoney(item.valor)} · {displayDate(item.data)}</li>)}</ul>{preview.length > 4 && <p>Mais {preview.length - 4} parcelas. Último vencimento: {displayDate(preview.at(-1)!.data)}.</p>}<p className={u.hint}>Os centavos são distribuídos entre as parcelas. Dias 29–31 são ajustados ao último dia de cada mês.</p></section>}
  </fieldset>{error && <p role="alert" className="error">{error}</p>}<div className={u.footer}><button className="button" disabled={isSubmitting || selecting}>{isSubmitting ? 'Registrando…' : 'Registrar comissão'}</button><button type="button" className="buttonGhost" disabled={isSubmitting || selecting} onClick={onClose}>Cancelar</button></div></form></Dialog>;
}
function PaymentDialog({ installment, onClose, onSaved }: { installment: CommissionInstallment; onClose: () => void; onSaved: () => void }) {
  const u = rentalUi, [error, setError] = useState('');
  const { register, handleSubmit, formState: { errors, isSubmitting } } = useForm<PaymentInput>({ resolver: zodResolver(paymentSchema), defaultValues: { confirmar_pagamento: false, observacao_pagamento: '' } });
  async function save(value: PaymentInput) { setError(''); try { await api.payCommissionInstallment(installment.id, value); onSaved(); onClose(); } catch (failure) { setError(errorMessage(failure)); } }
  return <Dialog title={`Receber parcela ${installment.numero_parcela}`} onClose={() => { if (!isSubmitting) onClose(); }}><form className={u.form} onSubmit={handleSubmit(save)} noValidate><p>{displayMoney(installment.valor)} · Vencimento {displayDate(installment.data_vencimento)}</p><fieldset disabled={isSubmitting}><label>Referência do comprovante<textarea placeholder="Ex.: PIX recebido em 14/09, comprovante nº…" {...register('observacao_pagamento')} aria-invalid={!!errors.observacao_pagamento} /><span className={u.error}>{errors.observacao_pagamento?.message}</span></label><label className="mt-4 flex! items-start gap-2.5!"><input className="w-auto!" type="checkbox" {...register('confirmar_pagamento')} />Confirmo que a imobiliária recebeu este pagamento.</label><p className={u.error}>{errors.confirmar_pagamento?.message}</p></fieldset>{error && <p role="alert" className="error">{error}</p>}<div className={u.footer}><button className="button" disabled={isSubmitting}>{isSubmitting ? 'Confirmando…' : 'Confirmar recebimento'}</button><button className="buttonGhost" type="button" disabled={isSubmitting} onClick={onClose}>Cancelar</button></div></form></Dialog>;
}
function EditCommission({ commission, onClose, onSaved }: { commission: Commission; onClose: () => void; onSaved: () => void }) {
  const u = rentalUi, [error, setError] = useState('');
  const { register, handleSubmit, formState: { errors, isSubmitting } } = useForm<{ ativo: boolean; observacoes: string }>({ resolver: zodResolver(commissionEditSchema), defaultValues: { ativo: commission.ativo, observacoes: commission.observacoes ?? '' } });
  async function save(value: { ativo: boolean; observacoes: string }) { setError(''); try { await api.updateCommission(commission.id, value); onSaved(); onClose(); } catch (failure) { setError(errorMessage(failure)); } }
  return <Dialog title="Editar comissão" onClose={() => { if (!isSubmitting) onClose(); }}><form className={u.form} onSubmit={handleSubmit(save)} noValidate><p>O valor total e as parcelas preservam o registro original. Ao desativar, novas baixas ficam bloqueadas e o histórico é mantido.</p><fieldset disabled={isSubmitting}><label>Observações<textarea {...register('observacoes')} /><span className={u.error}>{errors.observacoes?.message}</span></label><label className="mt-4 flex! items-center gap-2.5!"><input type="checkbox" className="w-auto!" {...register('ativo')} />Comissão ativa</label></fieldset>{error && <p role="alert" className="error">{error}</p>}<div className={u.footer}><button className="button" disabled={isSubmitting}>{isSubmitting ? 'Salvando…' : 'Salvar alterações'}</button><button type="button" className="buttonGhost" disabled={isSubmitting} onClick={onClose}>Cancelar</button></div></form></Dialog>;
}
function CommissionDetail({ id, onChanged }: { id: string; onChanged: () => void }) {
  const u = rentalUi, [paying, setPaying] = useState<CommissionInstallment>(), [editing, setEditing] = useState(false);
  const { data, loading, error, refresh } = useAdminData(useCallback(async () => {
    const commission = await api.getCommission(id);
    const [property, client] = await Promise.all([api.rentalPropertyOption(commission.imovel_id), api.rentalClientOption(commission.cliente_id)]);
    return { commission, property, client };
  }, [id]));
  function changed() { refresh(); onChanged(); }
  return <section className={u.panel}><AsyncState loading={loading} error={error} retry={refresh} />{data && !error && <><div className={u.heading}><div><h3 className={u.panelTitle}>{data.property.nome}</h3><p>Cliente: {data.client.nome} · {data.commission.ativo ? 'Comissão ativa' : 'Comissão arquivada'}</p></div><button className="buttonGhost" onClick={() => setEditing(true)}>Editar comissão</button></div>{data.commission.observacoes && <p className="whitespace-pre-wrap">{data.commission.observacoes}</p>}<div className={u.tableWrap}><table className={u.table}><thead><tr><th className={u.th}>Parcela</th><th className={u.th}>Vencimento</th><th className={u.th}>Valor</th><th className={u.th}>Recebimento</th></tr></thead><tbody>{data.commission.parcelas.map(item => <tr key={item.id}><td className={u.td}>{item.numero_parcela}</td><td className={u.td}>{displayDate(item.data_vencimento)}</td><td className={u.td}>{displayMoney(item.valor)}</td><td className={u.td}>{item.status === 'PAGO' ? <><strong>Pago</strong><p className={u.hint}>{item.pago_em ? new Date(item.pago_em).toLocaleString('pt-BR') : ''}</p><p className="whitespace-pre-wrap">{item.observacao_pagamento}</p></> : <><span>{item.status === 'ATRASADO' ? 'Atrasado' : 'Pendente'}</span>{data.commission.ativo && item.ativo && <button className="buttonGhost ml-3" onClick={() => setPaying(item)}>Registrar recebimento</button>}</>}</td></tr>)}</tbody></table></div>{editing && <EditCommission commission={data.commission} onClose={() => setEditing(false)} onSaved={changed} />}{paying && <PaymentDialog installment={paying} onClose={() => setPaying(undefined)} onSaved={changed} />}</>}</section>;
}
export default function Commissions({ lease }: { lease?: Lease }) {
  const u = rentalUi, [page, setPage] = useState(1), [active, setActive] = useState(true), [operation, setOperation] = useState<'' | 'LOCACAO' | 'VENDA'>(''), [creating, setCreating] = useState(false), [opened, setOpened] = useState('');
  const leaseId = lease?.id;
  const { data, loading, error, refresh } = useAdminData(useCallback(() => api.listCommissions({ pagina: page, limite: 15, ativo: active, tipo_operacao: operation || undefined, contrato_id: leaseId }), [page, active, operation, leaseId]));
  return <><header className={u.heading}><div>{lease ? <h2 className={u.panelTitle}>Comissões deste contrato</h2> : <h1 className={u.title}>Comissões</h1>}<p>Receita de intermediação da imobiliária.</p></div>{(!lease || lease.ativo) && <button className="button" onClick={() => setCreating(true)}>+ Registrar comissão</button>}</header><div className={u.toolbar}>{!lease && <label>Operação<select value={operation} onChange={event => { setOperation(event.target.value as typeof operation); setPage(1); setOpened(''); }}><option value="">Todas</option><option value="LOCACAO">Locação</option><option value="VENDA">Venda</option></select></label>}<label>Situação<select value={String(active)} onChange={event => { setActive(event.target.value === 'true'); setPage(1); setOpened(''); }}><option value="true">Ativas</option><option value="false">Arquivadas</option></select></label></div>
    <AsyncState loading={loading} error={error} retry={refresh} />{data && !error && <section className={u.panel}><div className={u.tableWrap}><table className={u.table}><thead><tr><th className={u.th}>Operação</th><th className={u.th}>Receita total</th><th className={u.th}>Recebido</th><th className={u.th}>Saldo</th><th className={u.th}>Parcelas</th></tr></thead><tbody>{data.itens.map(item => <tr key={item.id}><td className={u.td}>{item.tipo_operacao === 'VENDA' ? 'Venda' : 'Locação'}{item.observacoes && <small className="mt-1 block max-w-[200px] truncate text-muted">{item.observacoes}</small>}</td><td className={u.td}>{displayMoney(item.valor_total)}</td><td className={u.td}>{displayMoney(item.valor_pago ?? '0.00')}</td><td className={u.td}>{displayMoney(item.saldo_pendente ?? item.valor_total)}</td><td className={u.td}><button className="buttonGhost" aria-expanded={opened === item.id} onClick={() => setOpened(opened === item.id ? '' : item.id)}>{opened === item.id ? 'Ocultar' : `Ver ${item.quantidade_parcelas} parcela(s)`}</button></td></tr>)}</tbody></table></div>{!data.itens.length && <p>Nenhuma comissão registrada.</p>}<Pagination page={page} totalPages={Math.ceil(data.total / data.limite)} onChange={value => { setPage(value); setOpened(''); }} /></section>}{opened && data?.itens.some(item => item.id === opened) && <CommissionDetail id={opened} onChanged={refresh} />}{creating && <CommissionEditor lease={lease} onClose={() => setCreating(false)} onSaved={refresh} />}</>;
}
