import { routes } from '../../services/urls';
import { useCallback } from 'react';
import { Link } from 'react-router-dom';
import { api } from '../../services/api';
import { useAuth } from '../../hooks/useAuth';
import { date } from '../../services/format';
import AsyncState from '../../components/AsyncState';
import { useAdminData } from './useAdminData';
import styles from './Admin.module.css';
export default function Dashboard(){const {agent}=useAuth();const {data,loading,error,refresh}=useAdminData(useCallback(async()=>{const [properties,leads]=await Promise.all([api.listProperties({page:1,limit:1},true),api.listLeads({page:1,limit:5})]);return {properties,leads};},[]));return <><header className={styles.heading}><div><p className="eyebrow">VISÃO GERAL</p><h1>Olá, {agent?.name.split(' ')[0]}.</h1><p className="muted">Um olhar sobre suas próximas oportunidades.</p></div><Link className="button" to="/admin/imoveis/novo">+ Novo imóvel</Link></header><AsyncState loading={loading} error={error} retry={refresh}/>{data&&!error&&<><section className={styles.stats}><div className={styles.stat}><span>Imóveis no portfólio</span><strong>{data.properties.total}</strong><Link to="/admin/imoveis">Gerenciar imóveis →</Link></div><div className={styles.stat}><span>Contatos recebidos</span><strong>{data.leads.total}</strong><Link to={routes.contacts}>Ver oportunidades →</Link></div><div className={styles.stat}><span>Sua vitrine está pronta</span><strong>↗</strong><Link to={routes.home}>Explorar o site público</Link></div></section><section className={styles.panel}><h2>Contatos recentes</h2>{data.leads.items.length===0?<p className={styles.empty}>Os novos contatos aparecerão aqui.</p>:<div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Contato</th><th>Telefone</th><th>Recebido em</th></tr></thead><tbody>{data.leads.items.map(lead=><tr key={lead.id}><td><strong>{lead.leadName}</strong><small>{lead.leadEmail}</small></td><td>{lead.leadPhone}</td><td>{date(lead.createdAt)}</td></tr>)}</tbody></table></div>}</section></>}</>}
