import { useState } from 'react';
import { Navigate, Link, useNavigate, useLocation } from 'react-router-dom';
import { useForm } from 'react-hook-form';
import { z } from 'zod';
import { zodResolver } from '@hookform/resolvers/zod';
import { useAuth } from '../../hooks/useAuth';
import { brand,isDemo } from '../../config/brand';
import { errorMessage } from '../../services/format';
import styles from './Admin.module.css';
const schema=z.object({email:z.email('Informe um e-mail válido.'),password:z.string().min(1,'Informe sua senha.')});
export default function Login(){const {agent,login,loading}=useAuth();const navigate=useNavigate();const location=useLocation();const [error,setError]=useState('');const [demoBusy,setDemoBusy]=useState(false);const {register,handleSubmit,formState:{errors,isSubmitting}}=useForm<z.infer<typeof schema>>({resolver:zodResolver(schema)});async function enter(email:string,password:string){setError('');try{await login(email,password);const from=location.state?.from;navigate(typeof from==='string'&&from.startsWith('/admin')&&from!=='/admin/login'?from:'/admin',{replace:true});}catch(e){setError(errorMessage(e));}}if(agent)return <Navigate to="/admin" replace/>;return <div className={styles.login}><section className={styles.loginArt}><img className={styles.loginArtImage} src="/assets/commercial-space-source.jpg" srcSet="/assets/commercial-space-640.webp 640w, /assets/commercial-space-960.webp 960w, /assets/commercial-space-1400.webp 1400w" sizes="(max-width: 700px) 100vw, 50vw" width="1400" height="1050" alt="" {...{ fetchpriority: "high" }}/><Link to="/" className={styles.brand}>{brand.name}</Link><div><p className="eyebrow">SEU PRÓXIMO CAPÍTULO</p><h1>Boas conexões começam aqui.</h1><p>Seu portfólio, seus contatos e novas oportunidades.</p></div></section><main className={styles.loginContent}><div className={styles.loginForm}><p className="eyebrow">ÁREA DO CORRETOR</p><h1>Bem-vindo de volta.</h1><p className="muted">Entre para cuidar dos seus negócios.</p><form onSubmit={handleSubmit(v=>enter(v.email,v.password))} noValidate className={styles.form}><label>E-mail<input type="email" autoComplete="username" {...register('email')}/>{errors.email&&<span className={styles.errorText}>{errors.email.message}</span>}</label><label>Senha<input type="password" autoComplete="current-password" {...register('password')}/>{errors.password&&<span className={styles.errorText}>{errors.password.message}</span>}</label>{error&&<p className="error" role="alert">{error}</p>}<button className="button" disabled={isSubmitting||loading||demoBusy}>{isSubmitting?'Entrando…':'Entrar na conta →'}</button></form>{isDemo&&<div className={styles.demo}><p>Explore a demonstração com dados fictícios.</p><div className={styles.actions}>{(['admin','agent'] as const).map(role=><button key={role} className="buttonSecondary" disabled={demoBusy||isSubmitting} onClick={async()=>{setDemoBusy(true);await enter(`${role}@demo.local`,'demo');setDemoBusy(false);}}>{role==='admin'?'Administrador':'Corretor'}</button>)}</div></div>}<p><Link to="/">← Voltar ao site</Link></p></div></main></div>}
