import { describe,it,expect } from 'vitest';
import { propertyDraftKey,readPropertyDraft,writePropertyDraft,clearPropertyDraft } from './propertyDraft';

describe('Rascunho temporário do imóvel',()=>{
  it('preserva campos incompletos para restauração após autenticação',()=>{const key=propertyDraftKey('ana','imovel-1');writePropertyDraft(sessionStorage,key,{title:'',description:'Texto em andamento',price:25,featureValues:[{caracteristica_id:'',valor:'em edição'}]});expect(readPropertyDraft(sessionStorage,key)).toEqual({title:'',description:'Texto em andamento',price:25,featureValues:[{caracteristica_id:'',valor:'em edição'}]});clearPropertyDraft(sessionStorage,key);expect(readPropertyDraft(sessionStorage,key)).toBeNull();});
  it('isola rascunhos entre usuários e imóveis',()=>{expect(propertyDraftKey('ana','1')).not.toBe(propertyDraftKey('bia','1'));expect(propertyDraftKey('ana','1')).not.toBe(propertyDraftKey('ana','2'));expect(propertyDraftKey('ana')).not.toBe(propertyDraftKey('ana','1'));});
  it('não restaura senhas nem campos estranhos ao imóvel',()=>{sessionStorage.setItem('draft',JSON.stringify({title:'Galpão',password:'segredo',leadPhone:'5565999999999',agent:{password:'segredo'}}));expect(readPropertyDraft(sessionStorage,'draft')).toEqual({title:'Galpão'});});
  it('ignora armazenamento indisponível ou corrompido',()=>{sessionStorage.setItem('corrupt','{');expect(readPropertyDraft(sessionStorage,'corrupt')).toBeNull();const blocked={getItem(){throw new Error('blocked');},setItem(){throw new Error('blocked');},removeItem(){throw new Error('blocked');}};expect(()=>writePropertyDraft(blocked,'draft',{title:'Sala'})).not.toThrow();expect(readPropertyDraft(blocked,'draft')).toBeNull();expect(()=>clearPropertyDraft(blocked,'draft')).not.toThrow();});
  it('identifica conteúdo excessivo e quota excedida sem interromper a edição',()=>{expect(writePropertyDraft(sessionStorage,'large',{featureValues:[{caracteristica_id:'',valor:'x'.repeat(501)}]})).toBe('too_large');const quota={getItem(){return null;},setItem(){throw new DOMException('quota','QuotaExceededError');},removeItem(){return undefined;}};expect(writePropertyDraft(quota,'quota',{title:'Sala'})).toBe('quota');});
});
