import { useCallback,useState } from 'react';
import { Link } from 'react-router-dom';
import { api } from '../../services/api';
import { money,propertyStatuses,propertyType,errorMessage } from '../../services/format';
import AsyncState from '../../components/AsyncState';
import Pagination from '../../components/Pagination';
import { useAdminData } from './useAdminData';
import styles from './Admin.module.css';
export default function PropertyList(){const [page,setPage]=useState(1);const [mutationError,setMutationError]=useState('');const [busy,setBusy]=useState('');const {data,loading,error,refresh}=useAdminData(useCallback(()=>api.listProperties({page,limit:12},true),[page]));async function remove(id:string){if(!confirm('Excluir este imóvel e suas mídias? Esta ação não pode ser desfeita.'))return;setBusy(id);setMutationError('');try{await api.deleteProperty(id);if(data?.items.length===1&&page>1)setPage(page-1);else refresh();}catch(e){setMutationError(errorMessage(e));}finally{setBusy('');}}return <><header className={styles.heading}><div><p className="eyebrow">SEU PORTFÓLIO</p><h1>Imóveis</h1><p className="muted">Espaços bem apresentados, novas possibilidades.</p></div><Link className="button" to="/admin/imoveis/novo">+ Novo imóvel</Link></header>{mutationError&&<p className="error" role="alert">{mutationError}</p>}<AsyncState loading={loading} error={error} retry={refresh}/>{data&&!error&&<section className={styles.panel}>{!data.items.length?<div className={styles.empty}><h2>Seu portfólio começa aqui.</h2><p>Cadastre o primeiro imóvel para apresentá-lo no site.</p><Link to="/admin/imoveis/novo" className="button">Cadastrar imóvel</Link></div>:<><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Imóvel</th><th>Valor</th><th>Status</th><th>Ações</th></tr></thead><tbody>{data.items.map(p=><tr key={p.id}><td><strong>{p.title}</strong><small>{propertyType[p.type]} · {p.addressCity}/{p.addressState}</small></td><td>{money(p.price)}<small>{p.purpose==='LOCACAO'?'Por mês':'Venda'}</small></td><td><span className={styles.badge}>{propertyStatuses[p.status]}</span></td><td><div className={styles.actions}><Link to={`/admin/imoveis/${p.id}/editar`}>Editar</Link><Link to={`/imoveis/${p.slug}`}>Ver ↗</Link><button className={`buttonGhost ${styles.danger}`} disabled={!!busy} onClick={()=>void remove(p.id)}>{busy===p.id?'Excluindo…':'Excluir'}</button></div></td></tr>)}</tbody></table></div><Pagination page={page} totalPages={data.totalPages} onChange={setPage}/></>}</section>}</>}
